defmodule JoinBug.Repo.Migrations.AddMyResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:records, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :external_id, :text, null: false
      add :first_grantee_full_name, :text
      add :first_grantor_full_name, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end
  end

  def down do
    drop table(:records)
  end
end